[package]
name = "shader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = { version = "0.4.0-alpha.10", features = ["glam"] }
